CREATE TABLE ingestion_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    status VARCHAR(16) NOT NULL CHECK (status IN ('RUNNING', 'SUCCEEDED', 'FAILED')),
    processed INTEGER NOT NULL DEFAULT 0 CHECK (processed >= 0),
    inserted INTEGER NOT NULL DEFAULT 0 CHECK (inserted >= 0),
    updated INTEGER NOT NULL DEFAULT 0 CHECK (updated >= 0),
    unchanged INTEGER NOT NULL DEFAULT 0 CHECK (unchanged >= 0),
    error_message TEXT
);

CREATE INDEX idx_ingestion_run_started_at
    ON ingestion_run (started_at DESC);
